package com.testjunit.myjavaservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.testjunit.myjavaservice.MyJavaService;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link MyJavaService}.
 * @see MyJavaService
 */
@RestController
@Api(value = "MyJavaController", description = "controller class for java service execution")
@RequestMapping("/myJava")
public class MyJavaController {

    @Autowired
    private MyJavaService myJavaService;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/sampleJavaOperation", method = RequestMethod.GET)
    public String sampleJavaOperation() {
        return myJavaService.sampleJavaOperation();
    }
}

